nrf-rs/microbit

README.md
It took me some time to find the blog article, so for the benefit of the other folks who may check this crate (big thumbs up, BTW, for making this) - add the link to the blog post to the README
=> Add link to a blog with orientation

build.rs, memory.x
The section removed from memory.x is now the default.
build.rs will allow users of this crate to not need to include memory.x themselves.
=> Simplify memory.x and add build.rs for linking memory.x

examples/gpio_hal_printbuttons.rs, examples/gpio_hal_receivedcf77.rs, examples/i2c_direct_printmagserial.rs, examples/i2c_hal_printmagserial.rs, examples/i2c_haldriver_printmagserial.rs, examples/rng_direct_printrngserial.rs, examples/rng_hal_printrandserial.rs
This removes all usages of the deprecated `NVIC::enable` and replaces them with `NVIC::unmask`.
According to upstream `NVIC::enable` has a soundness issue and should be marked unsafe, which is why it was deprecated.
Fixes #18
=> Replaced NVIC::enable with NVIC::unmask

.github/workflows/ci.yaml, .gitignore, README.md, examples/led_nonblocking.rs, src/display/image.rs, src/led.rs
This adds a basic GitHub actions CI workflow. It includes `rustfmt`, `clippy` and `check`. The CI will not run on this PR because I'm opening it from a fork. If you would like to see it running before merging it you could push the branch to your repo and open a PR.
I have also added badges for crates.io and docs.rs as I often find them useful. If the CI proves useful I can add badge for that as well.
=> Add GitHub actions CI

Cargo.toml, examples/gpio_direct_blinky.rs, examples/gpio_hal_blinky.rs, examples/gpio_hal_ledbutton.rs, examples/gpio_hal_printbuttons.rs, examples/gpio_hal_receivedcf77.rs, examples/i2c_direct_printmagserial.rs, examples/i2c_hal_printmagserial.rs, examples/i2c_haldriver_printmagserial.rs, examples/led_blocking.rs, examples/led_nonblocking.rs, examples/led_rtfm.rs, examples/rng_direct_printrngserial.rs, examples/rng_hal_printrandserial.rs, examples/serial_direct_echo.rs, examples/serial_direct_helloworld.rs, examples/serial_hal_blocking_echo.rs, src/display/control.rs, src/display/mod.rs, src/display/timer.rs, src/led.rs, src/lib.rs
Relates to #27 
This is a large change down to the nrf51-hal API changing significantly between 0.7 and 0.10. While the upstream changes are significant I have tried to keep changes to the APIs published from this crate to a minimum. One exception to this is what is re-exported. I'm new to this domain so if the details I've provided aren't useful or there is useful information I haven't provided please let me know.
To make it easier to transition to supporting both the v1 and v2 microbits I have slightly tweaked the re-exports.
- `nrf51-hal` is still re-exported as `hal`
- `nrf51-hal::pac` is now re-exported as `pac`
- `nrf51-hal::nrf51::*` is no longer re-exported
This is the biggest change. The new timer interface is significantly stripped back so all of the interrupt and compare config …
=> Upgrade nrf51-hal to 0.12.1

examples/led_blocking.rs, src/gpio.rs, src/led.rs, src/lib.rs
This is an attempt to take small steps towards supporting the v2 board by tweaking APIs to make the inclusion easier.
In this step I map pins to the micro:bit names taken from the [v1.5 schematic](https://github.com/bbcmicrobit/hardware/tree/master/V1.5). I'm not sure what all the pins do so I've only included the mode where I'm fairly certain it's correct.
I have also moved the pins out of `led::Display::new` and into a separate struct. I've seen this done in nrf-hal and it seems to make it clearer what each pin is for. I think this will particularly helpful when introducing v2 as the pin layout is quite different.
=> Add GPIO pin names and extract LED pins

examples/led_blocking.rs, examples/led_nonblocking.rs, examples/led_rtfm.rs, src/display/control.rs, src/display/image.rs, src/display/mod.rs, src/gpio.rs, src/led.rs, src/lib.rs
In the micro:bit v2 the LED matrix pins are not placed next to each other. This change updates `display::control` so that it is configured with arrays of pin IDs rather than start and end IDs.
I would ideally like to change the interface of the `display` module so that it doesn't take a mutable reference to the `pac::Periferals::GPIO` instance. As far as I can tell taking a mutable reference to `GPIO` means that the hal can't be used for the other pins as `hal::gpio::p0::Parts` requires ownership of `GPIO`. I think it's done like this for performance reasons so that multiple pins can be set high or low at once but it seems like a very high price to pay.
If we could change the interface to be around `hal::gpio::Pin` instances we could reuse the `Pins` struct from #33
I am not confident in …
=> Allow noncontiguous pins in display

CHANGELOG.md, Cargo.toml
See #35
- Add `microbit::gpio` module with pins mapped to micro:bit names
- Refactor `microbit::display` and `microbit::led` to accept `gpio::Pins`
- Make probe-run the default runner
- Rewrite `serial_port` as a macro
- Fix rustdoc warnings
- Upgrade nrf51-hal to 0.12.1
=> Bump version to v0.9.0

.github/workflows/changelog.yml, .github/workflows/ci.yaml, .github/workflows/clippy.yml, .github/workflows/rustfmt.yml
This also adds in the `labeled` and `unlabeled` types for the changelog workflow so that it is re-run when the `no changelog` label is added.
I had some difficulty with the changelog workflow. It doesn't always seem to correctly detect if the PR has the `no changelog` label.
=> update github actions for new main

README.md
I hadn't realised what a big difference it makes.
=> Add `--release` flag to README examples

xtask/Cargo.toml, xtask/src/bump.rs
- check for the correct (no changes) string
- insert the new version link in the correct place
=> Minor fixes to xtask bump

CHANGELOG.md, examples/display-blocking/src/main.rs, examples/display-nonblocking/src/main.rs, examples/display-rtic/src/main.rs, examples/gpio-hal-blinky/src/main.rs, examples/gpio-hal-ledbutton/src/main.rs, examples/gpio-hal-printbuttons/Cargo.toml, examples/gpio-hal-printbuttons/src/main.rs, examples/rng-hal/src/main.rs, examples/serial-hal-blocking-echo/src/main.rs, examples/v2-speaker/src/main.rs, microbit-common/src/board.rs, microbit-common/src/display/blocking.rs, microbit-common/src/display/nonblocking/mod.rs, microbit-common/src/lib.rs, microbit-common/src/v1/board.rs, microbit-common/src/v1/mod.rs, microbit-common/src/v2/board.rs, microbit-common/src/v2/mod.rs
Introduce a Board struct similar to those in other nrf-rs board support crates. This makes for a much nicer API and allows for pretty much all of the feature switching to be removed from the examples.
I have added all the core peripherals but not all the peripherals yet as this doesn't seem to be what is done in the other BSPs. I have added all peripherals that are used in the examples so far.
As a quick example of how this improves things. Instead of doing this:
```rust
let p = pac::Peripherals::take().unwrap();
let mut timer = Timer::new(p.TIMER0);
// Set up pins
#[cfg(feature = "v1")]
let pins = {
let p0parts = P0Parts::new(p.GPIO);
display_pins!(p0parts)
};
#[cfg(feature = "v2")]
let pins = {
let p0parts = P0Parts::new(p.P0);
let p1parts = P1Parts::new(p.P1);
display_pins!(p0parts, …
```
=> Introduce Board struct

CHANGELOG.md, examples/magnetometer/Cargo.toml, examples/magnetometer/src/main.rs, microbit-common/src/v1/board.rs, microbit-common/src/v1/gpio.rs, microbit-common/src/v2/board.rs, microbit-common/src/v2/gpio.rs
Uses LSM303AGR driver from eldruin mentioned here #27 (comment)
This example works on the micro:bit V1.5 and V2. The micro:bit V1.3 uses a different magnetometer.
Depends on #60 but does not need to
=> Add magnetometer example

CHANGELOG.md, examples/serial-hal-blocking-echo/Cargo.toml, examples/serial-hal-blocking-echo/src/main.rs, examples/serial-hal-blocking-echo/src/serial_setup.rs, examples/v2-speaker/src/main.rs, microbit-common/Cargo.toml, microbit-common/src/display/blocking.rs, microbit-common/src/v1/board.rs, microbit-common/src/v2/board.rs, microbit-common/src/v2/gpio.rs, microbit/src/lib.rs
This implements an abstraction for UARTE, very similar to the general I2C abstracttion. At the moment the example doesn't compile for nrf52833 yet, once https://github.com/nrf-rs/nrf-hal/pull/281 is finally merged that should be fairly trivial to do though.
=> Initial UART(E) implementation

.github/bors.toml, .github/workflows/ci.yaml, CHANGELOG.md, microbit-common/Cargo.toml, microbit-common/src/lib.rs, microbit-v2/Cargo.toml, microbit-v2/src/lib.rs, microbit/Cargo.toml, microbit/src/lib.rs
See: [CHANGELOG.md](/CHANGELOG.md)
- Added support for the thumbv7em-none-eabi target for microbit:v2 (same as
thumbv7em-none-eabihf but without hardware floating point support)
- Rearrange LED display modules under the same root module and change their
APIs to be more aligned with each other.
- Add BLE Beacon demo.
- Add a simple speaker demo for micro:bit V2.
- Add Board struct following the pattern used in other nrf board support crates.
- Add magnetometer example.
- LEDs on the micro:bit V1 are now turned off per default
- UART(E) is now exposed in the same way as I2C
=> Bump version to 0.11.0

CHANGELOG.md, examples/ble-beacon/Cargo.toml, examples/display-nonblocking/Cargo.toml, examples/display-rtic/Cargo.toml, microbit-common/Cargo.toml
The unreleased fix is now released in 0.14.0 so pulling 0.13.0 from git is no longer needed (and no longer works without pinning to a commit).
However, this changes the `cortex-m` version from 0.6.x to 0.7.3 which causes problems for some of the examples where the old `cortex-m` is still brought in by other dependencies. The fix for the `display-rtic` example is to use the `cortex-m-7` feature until `cortex-m-rtic` 0.6 is released. For `rubble` the only fix I could find was to grab the git version as it does use the latest `nrf5x` pac there it's just not released yet.
=> Update nrf-hal dependencies

.github/bors.toml, .github/workflows/ci.yaml
This change fixes the issue where bors times out waiting for a build that does not exist whenever we change the MSRV.
See [this comment](https://github.com/nrf-rs/microbit/pull/64#issuecomment-918124858)
=> Fix issue with version number in bors config

CHANGELOG.md, microbit-common/src/v1/board.rs, microbit-common/src/v2/board.rs
I needed to use board features as well as the cpu temp that was currently only available from the peripherals. 
I would prefer to even include it in the board directly similar to the buttons or add a function to the board the returns the temp struct to make it more simple to use. Is this an desired improvement or too much bloat?
=> Add temp peripheral to board

CHANGELOG.md, examples/display-nonblocking/src/main.rs
The nonblocking display example is not working properly. I fixed it by removing ```Peripherals::take()``` and using the ```board``` variable as ```mut```
=> fix display-nonblocking example

CHANGELOG.md, examples/display-rtic/src/main.rs, microbit-common/src/v1/board.rs, microbit-common/src/v2/board.rs
Fixes #73 thanks to the help of @korken89 in the rtic matrix.
RTIC takes the core peripherals already for its own context. There board should take these directly from the context for its own creation.
=> Make `Board::new(p, cp)` pub and fix RTIC example

CHANGELOG.md, microbit-common/src/display/nonblocking/control.rs
Currently when cycling through the outer leds of the display in the nonblocking mode the order is broken for the top & bottom row. The current order is 1->4->3->2->5.
This PR fixes the issue some of the columns were mixed up and matches with the docs from the microbit.
It can be tested by replacing the display_nonblocking example with the slightly modified example here: https://gist.github.com/7b8d71b6b06eb8ab11a5f5f0a13f7a47
=> Fix wrong order of display columns

CHANGELOG.md, microbit-common/src/display/nonblocking/timer.rs
The ```fn disable_secondary(&mut self) ``` function for the display timer did not work. This caused a crash when a GrayScaleImage had a row with just 0-Values.
=> Fix timer for LED-display (GreyscaleImage with a empty Row did not work)

CHANGELOG.md, examples/display-text-rtic/Cargo.toml, examples/display-text-rtic/src/main.rs
The implementation is in a separate [`microbit-text`] crate as discussed in #78.
I've tested on micro:bit v1 only.
I did the example using RTIC, but I can just as easily do it without (or both ways).
Does this look sensible? If everyone's happy with `microbit-text` as it stands I can make it v1.0.0.
[`microbit-text`]: https://github.com/mattheww/microbit-text
=> Add an example of scrolling text

.github/workflows/clippy.yml, microbit-common/src/v1/board.rs, microbit-common/src/v2/board.rs
The `--examples` flag is no longer working. It has been silently failing since the examples moved to full crates rather modules.
=> Run clippy against main packages

.github/workflows/ci.yaml, CHANGELOG.md
This will let us use dependencies that need Rust 2021 in examples.
As discussed at https://github.com/nrf-rs/microbit/pull/80#issuecomment-977001166 and https://github.com/nrf-rs/microbit/pull/83#issuecomment-1035592387 .
=> Bump MSRV to 1.57

CHANGELOG.md, examples/analog-v1/src/main.rs, examples/analog-v2/src/main.rs, examples/analog/Cargo.toml, examples/analog/src/main.rs, examples/servo/Cargo.toml, examples/servo/src/main.rs, examples/v2-microphone/src/main.rs, microbit-common/src/adc.rs, microbit-common/src/lib.rs, microbit-common/src/v1/adc.rs, microbit-common/src/v1/board.rs, microbit-common/src/v1/gpio.rs, microbit-common/src/v1/mod.rs, microbit-common/src/v2/adc.rs, microbit-common/src/v2/board.rs, microbit-common/src/v2/gpio.rs, microbit-common/src/v2/mod.rs
Hi,
I have added common type aliases and structs for the GPIO pins on the edge connector. I did the same for ADC and SAADC with a common default initialization for 10 bit resolution. It is now possible to use the same code for v1 and v2 if the extra capabilities of v2 are not needed. There is also a new analog example using the common interface and a TIMER, GPIOTE and PPI servo example.
Cheers, Torsten
=> Unify names

CHANGELOG.md, microbit-common/src/display/blocking.rs
The calculation in `display::blocking::Display::set_refresh_rate` was wrong for the micro:bit v2.
For example, `set_refresh_rate(60)` gave a refresh rate of 36Hz rather than 60Hz.
To see the difference, add
````
display.set_refresh_rate(60);
````
to `examples/display-blocking/src/main.rs`
=> Fix blocking::Display::set_refresh_rate()

CHANGELOG.md, microbit-common/src/display/nonblocking/control.rs
Closes #108
On the micro:bit v2 the GPIO pins are on two ports, and it takes four IO writes to update all the pins: one "clear multiple pins" and one "set multiple pins" per port.
(It's possible to set pins to both low and high using `OUT`, but we can't use that as we don't own all the pins on the port.)
So there is a brief period where the pins are in a mix of the old and new states, and evidently in debug builds this can persist for long enough to be visible.
We can fix this by changing the order of writes: make the first write be the one that makes the old row dark, and the last one be the one that makes the new row light.
We might as well also arrange the code so that it doesn't perform any calculations between the GPIO writes (on the theory that in debug mode the compiler probably …
=> Non-blocking display: change the order of GPIO writes

CHANGELOG.md, microbit-common/src/v1/board.rs, microbit-common/src/v2/board.rs
My motivation for this was to use the SPI. I'm not sure if the idea was not to export all peripherals just to keep the API clean (or for some other reason), so fell free to close the PR if this doesn't fit the crate's goals.
=> export all peripherals

CHANGELOG.md, Cargo.toml, examples/analog-v1/Cargo.toml, examples/analog-v1/src/main.rs, examples/analog-v2/Cargo.toml, examples/analog-v2/src/main.rs, examples/analog/Cargo.toml, examples/analog/src/main.rs, examples/display-blocking/Cargo.toml, examples/display-blocking/src/main.rs, examples/display-nonblocking/src/main.rs, examples/gpio-hal-ledbutton/Cargo.toml, examples/gpio-hal-ledbutton/src/main.rs, examples/magnetometer/Cargo.toml, examples/magnetometer/src/main.rs, examples/serial-hal-blocking-echo/src/main.rs, examples/v2-microphone/src/main.rs, examples/v2-speaker/src/main.rs, microbit-common/Cargo.toml, microbit-common/src/display/blocking.rs
For now this still uses `embedded-hal` 0.2, the update to using 1.0 traits will be a separate PR.
=> Update HAL crates

CHANGELOG.md, README.md
The binary `probe-rs` tools has been moved to it's own crate: `probe-rs-tools`. Therefore, the current instructions are outdated and fail:
```bash
$ cargo install probe-rs
Updating crates.io index
Downloaded probe-rs v0.24.0
Downloaded 1 crate (1.7 MB) in 0.35s
error: there is nothing to install in `probe-rs v0.24.0`, because it has no binaries
`cargo install` is only for installing programs, and can't be used with libraries.
To use a library crate, add it as a dependency to a Cargo project with `cargo add`.
```
This commit updates the installation instruction.
For more information, see the [probe-rs' changelog][^1].
[^1]: https://github.com/probe-rs/probe-rs/blob/master/CHANGELOG.md#0240
=> Update installation instruction for `probe-rs`

CHANGELOG.md, microbit-common/src/v1/board.rs, microbit-common/src/v2/board.rs, microbit-v2/Cargo.toml, microbit/Cargo.toml
Made the `sda` and `scl` pins in the various `I2c` `Pins` struct public.
Closes #150
=> made sda and scl public for i2c interfaces

CHANGELOG.md, README.md
Don't have a current link for the microbit-Rust-on-Windows blog entry in the README, so just deleted it for now.
closes #157. closes #162
=> removed broken link

.github/workflows/ci.yaml, CHANGELOG.md
This is required to build the latest version of flip-link, which is used in our CI.
=> Bump MSRV to 1.81.0.
