examples/led_blocking.rs, src/led.rs, src/lib.rs
Simple driver implementation for LED display.
The implementation scans through the 3 matrix rows fast enough to display the image without flickering.
@therealprof this follows on from our discussion earlier. It appears to work pretty well.
=> LED display, demo blocking scan line implementation

README.md
Add links to own examples, and the MicroRust book.
Shameless advertising.
=> update README, add more reading links

Cargo.toml, examples/led_blocking.rs, src/led.rs
Warning: breaking led interface change
retain pin types on interface
other cleanups:
+ removing unused dependency
+ advice from clippy
=> Change LED display interface to be type safe, other cleanup

examples/gpio_hal_printbuttons.rs, examples/gpio_hal_receivedcf77.rs, examples/i2c_hal_printmagserial.rs, examples/i2c_haldriver_printmagserial.rs, examples/rng_hal_printrandserial.rs, src/led.rs, src/lib.rs
Use 'into' instead of 'downgrade'
=> Small refactoring

README.md
Signed-off-by: ed neville <ed@s5h.net>
=> Adjusting wording flow for readability

examples/i2c_hal_printmagserial.rs, src/lib.rs
This addresses the FIXME comment.
=> Rewrite serial_port as a macro

.github/scripts/build-examples.sh, .github/workflows/ci.yaml, examples/serial_hal_blocking_echo.rs
=> Build examples in CI

.github/bors.toml, .github/workflows/changelog.yml, .github/workflows/clippy.yml, .github/workflows/rustfmt.yml
=> Add bors and more GHA workflows

CHANGELOG.md, microbit-common/Cargo.toml, microbit-common/src/lib.rs, microbit-v2/Cargo.toml, microbit-v2/src/lib.rs, microbit/Cargo.toml, microbit/src/lib.rs
=> Bump version to v0.10.0

xtask/src/ci.rs
The output of `cargo xtask ci` is quite noisy and it can be hard to see exactly what has failed. This change adds GitHub actions workflow grouping to make it a bit easier to read.
https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#grouping-log-lines
=> Group CI steps when running in GitHub actions

.cargo/config.toml, CHANGELOG.md
=> Add thumbv7em-none-eabi support to config.toml

xtask/src/bump.rs, xtask/src/ci.rs, xtask/src/lib.rs, xtask/src/main.rs, xtask/src/publish.rs
Also fix typo in the compare URL in xtask bump.
=> Add xtask to publish crates to crates.io

microbit-v2/src/lib.rs
Fix small left/right mistake in the docs of the micro:bit v2
=> Fix small mistake (left/right)

CHANGELOG.md, microbit-common/Cargo.toml, microbit-common/src/lib.rs, microbit-v2/Cargo.toml, microbit-v2/src/lib.rs, microbit/Cargo.toml, microbit/src/lib.rs
- Update dependencies nrf51-hal and nrf52833-hal to 0.14.0
=> Bump version to 0.12.0

CHANGELOG.md, microbit-common/Cargo.toml, microbit-common/src/lib.rs, microbit-v2/Cargo.toml, microbit-v2/src/lib.rs, microbit/Cargo.toml, microbit/src/lib.rs
=> Bump version to 0.13 to get the discovery book out of a pickle

CHANGELOG.md, examples/display-rtic/Cargo.toml, examples/display-rtic/src/main.rs, examples/display-text-rtic/Cargo.toml, examples/display-text-rtic/src/main.rs
I've tested these with a micro:bit v1 only.
=> Update RTIC examples to use cortex-m-rtic 1.0

.github/workflows/ci.yaml, CHANGELOG.md
=> Bump MSRV to 1.61 as required by the fixed crate

CHANGELOG.md, examples/display-blocking/Cargo.toml, examples/display-nonblocking/Cargo.toml, examples/display-rtic/Cargo.toml, examples/display-text-rtic/Cargo.toml, examples/gpio-direct-blinky/Cargo.toml, examples/gpio-hal-blinky/Cargo.toml, examples/gpio-hal-ledbutton/Cargo.toml, examples/gpio-hal-printbuttons/Cargo.toml, examples/magnetometer/Cargo.toml, examples/rng-direct/Cargo.toml, examples/rng-hal/Cargo.toml, examples/serial-direct-echo/Cargo.toml, examples/serial-direct-helloworld/Cargo.toml, examples/serial-hal-blocking-echo/Cargo.toml, examples/v2-microphone/Cargo.toml, examples/v2-speaker/Cargo.toml, microbit-common/src/display/nonblocking/image.rs, xtask/Cargo.toml
=> Bump dependency versions to latest for all examples

CHANGELOG.md, microbit-common/src/v1/board.rs
=> add ADC functionality to Board

CHANGELOG.md, microbit-common/src/v2/board.rs
=> v2: Add RTC1 and RTC2 to Board

CHANGELOG.md, microbit-common/src/v2/board.rs
This is a do-over of #100 (and #105), but targeting the main branch instead of staging.
closes https://github.com/nrf-rs/microbit/issues/99
=> Add missing rtcs

CHANGELOG.md, microbit-common/src/display/blocking.rs, microbit-common/src/display/nonblocking/mod.rs
=> Updated non-blocking display documenation and added Changelog entry

CHANGELOG.md, microbit-common/src/display/nonblocking/mod.rs, microbit-common/src/display/nonblocking/timer.rs
=> Double the non-blocking display refresh frequency for the micro:bit V2

CHANGELOG.md, examples/analog-v1/Cargo.toml, examples/analog-v2/Cargo.toml, examples/analog/Cargo.toml, examples/display-blocking/Cargo.toml, examples/display-nonblocking/Cargo.toml, examples/display-rtic/Cargo.toml, examples/display-text-rtic/Cargo.toml, examples/gpio-direct-blinky/Cargo.toml, examples/gpio-hal-blinky/Cargo.toml, examples/gpio-hal-ledbutton/Cargo.toml, examples/gpio-hal-printbuttons/Cargo.toml, examples/magnetometer/Cargo.toml, examples/magnetometer/src/main.rs, examples/rng-direct/Cargo.toml, examples/rng-hal/Cargo.toml, examples/serial-direct-echo/Cargo.toml, examples/serial-direct-helloworld/Cargo.toml, examples/servo/Cargo.toml, examples/v2-microphone/Cargo.toml, examples/v2-speaker/Cargo.toml, microbit-common/Cargo.toml, xtask/Cargo.toml, xtask/src/bump.rs
This updates various other dependencies to the latest version, or latest compatible version. A few minor code changes were required.
=> Update more dependencies

CHANGELOG.md, microbit-common/Cargo.toml, microbit-common/src/lib.rs, microbit-v2/Cargo.toml, microbit-v2/src/lib.rs, microbit/Cargo.toml, microbit/src/lib.rs
=> Prepare for 0.15.0 release.

.github/workflows/ci.yaml, CHANGELOG.md, Cargo.lock, microbit-common/Cargo.toml, microbit-v2/Cargo.toml, microbit/Cargo.toml
=> Run cargo update and bump MSRV.
